/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedTradesRouteImport } from './routes/_authenticated/trades'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedScannerRouteImport } from './routes/_authenticated/scanner'
import { Route as AuthenticatedSaasRouteImport } from './routes/_authenticated/saas'
import { Route as AuthenticatedRiskCenterRouteImport } from './routes/_authenticated/risk-center'
import { Route as AuthenticatedRetailRouteImport } from './routes/_authenticated/retail'
import { Route as AuthenticatedOpportunitiesRouteImport } from './routes/_authenticated/opportunities'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMarketRouteImport } from './routes/_authenticated/market'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedFreightRouteImport } from './routes/_authenticated/freight'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCorridorsRouteImport } from './routes/_authenticated/corridors'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedApiConsoleRouteImport } from './routes/_authenticated/api-console'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedTradesTradeIdRouteImport } from './routes/_authenticated/trades.$tradeId'
import { Route as ApiPublicV1DataRouteImport } from './routes/api/public/v1/data'
import { Route as ApiPublicCronRefreshPricesRouteImport } from './routes/api/public/cron/refresh-prices'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTradesRoute = AuthenticatedTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScannerRoute = AuthenticatedScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSaasRoute = AuthenticatedSaasRouteImport.update({
  id: '/saas',
  path: '/saas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRiskCenterRoute = AuthenticatedRiskCenterRouteImport.update({
  id: '/risk-center',
  path: '/risk-center',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRetailRoute = AuthenticatedRetailRouteImport.update({
  id: '/retail',
  path: '/retail',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOpportunitiesRoute =
  AuthenticatedOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketRoute = AuthenticatedMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFreightRoute = AuthenticatedFreightRouteImport.update({
  id: '/freight',
  path: '/freight',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCorridorsRoute = AuthenticatedCorridorsRouteImport.update({
  id: '/corridors',
  path: '/corridors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApiConsoleRoute = AuthenticatedApiConsoleRouteImport.update({
  id: '/api-console',
  path: '/api-console',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTradesTradeIdRoute =
  AuthenticatedTradesTradeIdRouteImport.update({
    id: '/$tradeId',
    path: '/$tradeId',
    getParentRoute: () => AuthenticatedTradesRoute,
  } as any)
const ApiPublicV1DataRoute = ApiPublicV1DataRouteImport.update({
  id: '/api/public/v1/data',
  path: '/api/public/v1/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRefreshPricesRoute =
  ApiPublicCronRefreshPricesRouteImport.update({
    id: '/api/public/cron/refresh-prices',
    path: '/api/public/cron/refresh-prices',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/terms': typeof TermsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/api-console': typeof AuthenticatedApiConsoleRoute
  '/chat': typeof AuthenticatedChatRoute
  '/corridors': typeof AuthenticatedCorridorsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/freight': typeof AuthenticatedFreightRoute
  '/help': typeof AuthenticatedHelpRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/market': typeof AuthenticatedMarketRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/retail': typeof AuthenticatedRetailRoute
  '/risk-center': typeof AuthenticatedRiskCenterRoute
  '/saas': typeof AuthenticatedSaasRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/trades': typeof AuthenticatedTradesRouteWithChildren
  '/wallet': typeof AuthenticatedWalletRoute
  '/api/chat': typeof ApiChatRoute
  '/trades/$tradeId': typeof AuthenticatedTradesTradeIdRoute
  '/api/public/cron/refresh-prices': typeof ApiPublicCronRefreshPricesRoute
  '/api/public/v1/data': typeof ApiPublicV1DataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/terms': typeof TermsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/api-console': typeof AuthenticatedApiConsoleRoute
  '/chat': typeof AuthenticatedChatRoute
  '/corridors': typeof AuthenticatedCorridorsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/freight': typeof AuthenticatedFreightRoute
  '/help': typeof AuthenticatedHelpRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/market': typeof AuthenticatedMarketRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/retail': typeof AuthenticatedRetailRoute
  '/risk-center': typeof AuthenticatedRiskCenterRoute
  '/saas': typeof AuthenticatedSaasRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/trades': typeof AuthenticatedTradesRouteWithChildren
  '/wallet': typeof AuthenticatedWalletRoute
  '/api/chat': typeof ApiChatRoute
  '/trades/$tradeId': typeof AuthenticatedTradesTradeIdRoute
  '/api/public/cron/refresh-prices': typeof ApiPublicCronRefreshPricesRoute
  '/api/public/v1/data': typeof ApiPublicV1DataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/api-console': typeof AuthenticatedApiConsoleRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/corridors': typeof AuthenticatedCorridorsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/freight': typeof AuthenticatedFreightRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/market': typeof AuthenticatedMarketRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/_authenticated/retail': typeof AuthenticatedRetailRoute
  '/_authenticated/risk-center': typeof AuthenticatedRiskCenterRoute
  '/_authenticated/saas': typeof AuthenticatedSaasRoute
  '/_authenticated/scanner': typeof AuthenticatedScannerRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/trades': typeof AuthenticatedTradesRouteWithChildren
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/trades/$tradeId': typeof AuthenticatedTradesTradeIdRoute
  '/api/public/cron/refresh-prices': typeof ApiPublicCronRefreshPricesRoute
  '/api/public/v1/data': typeof ApiPublicV1DataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/safety'
    | '/terms'
    | '/analytics'
    | '/api-console'
    | '/chat'
    | '/corridors'
    | '/dashboard'
    | '/freight'
    | '/help'
    | '/history'
    | '/home'
    | '/journal'
    | '/market'
    | '/notifications'
    | '/opportunities'
    | '/retail'
    | '/risk-center'
    | '/saas'
    | '/scanner'
    | '/search'
    | '/settings'
    | '/trades'
    | '/wallet'
    | '/api/chat'
    | '/trades/$tradeId'
    | '/api/public/cron/refresh-prices'
    | '/api/public/v1/data'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/safety'
    | '/terms'
    | '/analytics'
    | '/api-console'
    | '/chat'
    | '/corridors'
    | '/dashboard'
    | '/freight'
    | '/help'
    | '/history'
    | '/home'
    | '/journal'
    | '/market'
    | '/notifications'
    | '/opportunities'
    | '/retail'
    | '/risk-center'
    | '/saas'
    | '/scanner'
    | '/search'
    | '/settings'
    | '/trades'
    | '/wallet'
    | '/api/chat'
    | '/trades/$tradeId'
    | '/api/public/cron/refresh-prices'
    | '/api/public/v1/data'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/safety'
    | '/terms'
    | '/_authenticated/analytics'
    | '/_authenticated/api-console'
    | '/_authenticated/chat'
    | '/_authenticated/corridors'
    | '/_authenticated/dashboard'
    | '/_authenticated/freight'
    | '/_authenticated/help'
    | '/_authenticated/history'
    | '/_authenticated/home'
    | '/_authenticated/journal'
    | '/_authenticated/market'
    | '/_authenticated/notifications'
    | '/_authenticated/opportunities'
    | '/_authenticated/retail'
    | '/_authenticated/risk-center'
    | '/_authenticated/saas'
    | '/_authenticated/scanner'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/trades'
    | '/_authenticated/wallet'
    | '/api/chat'
    | '/_authenticated/trades/$tradeId'
    | '/api/public/cron/refresh-prices'
    | '/api/public/v1/data'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  SafetyRoute: typeof SafetyRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicCronRefreshPricesRoute: typeof ApiPublicCronRefreshPricesRoute
  ApiPublicV1DataRoute: typeof ApiPublicV1DataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trades': {
      id: '/_authenticated/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof AuthenticatedTradesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scanner': {
      id: '/_authenticated/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof AuthenticatedScannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saas': {
      id: '/_authenticated/saas'
      path: '/saas'
      fullPath: '/saas'
      preLoaderRoute: typeof AuthenticatedSaasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/risk-center': {
      id: '/_authenticated/risk-center'
      path: '/risk-center'
      fullPath: '/risk-center'
      preLoaderRoute: typeof AuthenticatedRiskCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/retail': {
      id: '/_authenticated/retail'
      path: '/retail'
      fullPath: '/retail'
      preLoaderRoute: typeof AuthenticatedRetailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/opportunities': {
      id: '/_authenticated/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AuthenticatedOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market': {
      id: '/_authenticated/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AuthenticatedMarketRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/freight': {
      id: '/_authenticated/freight'
      path: '/freight'
      fullPath: '/freight'
      preLoaderRoute: typeof AuthenticatedFreightRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/corridors': {
      id: '/_authenticated/corridors'
      path: '/corridors'
      fullPath: '/corridors'
      preLoaderRoute: typeof AuthenticatedCorridorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-console': {
      id: '/_authenticated/api-console'
      path: '/api-console'
      fullPath: '/api-console'
      preLoaderRoute: typeof AuthenticatedApiConsoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trades/$tradeId': {
      id: '/_authenticated/trades/$tradeId'
      path: '/$tradeId'
      fullPath: '/trades/$tradeId'
      preLoaderRoute: typeof AuthenticatedTradesTradeIdRouteImport
      parentRoute: typeof AuthenticatedTradesRoute
    }
    '/api/public/v1/data': {
      id: '/api/public/v1/data'
      path: '/api/public/v1/data'
      fullPath: '/api/public/v1/data'
      preLoaderRoute: typeof ApiPublicV1DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/refresh-prices': {
      id: '/api/public/cron/refresh-prices'
      path: '/api/public/cron/refresh-prices'
      fullPath: '/api/public/cron/refresh-prices'
      preLoaderRoute: typeof ApiPublicCronRefreshPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedTradesRouteChildren {
  AuthenticatedTradesTradeIdRoute: typeof AuthenticatedTradesTradeIdRoute
}

const AuthenticatedTradesRouteChildren: AuthenticatedTradesRouteChildren = {
  AuthenticatedTradesTradeIdRoute: AuthenticatedTradesTradeIdRoute,
}

const AuthenticatedTradesRouteWithChildren =
  AuthenticatedTradesRoute._addFileChildren(AuthenticatedTradesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedApiConsoleRoute: typeof AuthenticatedApiConsoleRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedCorridorsRoute: typeof AuthenticatedCorridorsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFreightRoute: typeof AuthenticatedFreightRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedMarketRoute: typeof AuthenticatedMarketRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOpportunitiesRoute: typeof AuthenticatedOpportunitiesRoute
  AuthenticatedRetailRoute: typeof AuthenticatedRetailRoute
  AuthenticatedRiskCenterRoute: typeof AuthenticatedRiskCenterRoute
  AuthenticatedSaasRoute: typeof AuthenticatedSaasRoute
  AuthenticatedScannerRoute: typeof AuthenticatedScannerRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTradesRoute: typeof AuthenticatedTradesRouteWithChildren
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedApiConsoleRoute: AuthenticatedApiConsoleRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedCorridorsRoute: AuthenticatedCorridorsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFreightRoute: AuthenticatedFreightRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedMarketRoute: AuthenticatedMarketRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOpportunitiesRoute: AuthenticatedOpportunitiesRoute,
  AuthenticatedRetailRoute: AuthenticatedRetailRoute,
  AuthenticatedRiskCenterRoute: AuthenticatedRiskCenterRoute,
  AuthenticatedSaasRoute: AuthenticatedSaasRoute,
  AuthenticatedScannerRoute: AuthenticatedScannerRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTradesRoute: AuthenticatedTradesRouteWithChildren,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  SafetyRoute: SafetyRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicCronRefreshPricesRoute: ApiPublicCronRefreshPricesRoute,
  ApiPublicV1DataRoute: ApiPublicV1DataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
